spring:
  liquibase:
    change-log: /db/changelog/root-changelog.xml
    driver-class-name: org.mariadb.jdbc.Driver
    user: test
    password: test
  datasource:
    url: jdbc:mariadb://localhost:3306/omega_legacy
    username: test
    password: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  batch:
    jdbc:
      initialize-schema: always