spring:
  liquibase:
    change-log: /db/changelog/root-changelog.xml
    driver-class-name: org.mariadb.jdbc.Driver
    user: test
    password: test
  datasource:
    url: jdbc:mariadb://localhost:3306/omega_legacy
    username: test
    password: test
  batch:
    jdbc:
      initialize-schema: always
  kafka:
    bootstrap-servers: localhost:9092
server:
  port: 8082